import type { CaptionTemplate } from "@/types";

export const CAPTION_TEMPLATES: CaptionTemplate[] = [

  // ── Trending word-highlight templates ───────────────────────────────────
  // Style: all words visible, current word highlighted + pops

  {
    id: "insta-karaoke",
    name: "Insta Karaoke",
    description: "All words shown, active word pops yellow",
    icon: "🔥",
    category: "trending",
    wordByWord: true,
    position: "bottom",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "12px 20px",
      background: "rgba(0,0,0,0.72)",
      borderRadius: "14px",
      backdropFilter: "blur(6px)",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "6px",
      textAlign: "center",
    },
    textStyle: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "26px",
      fontWeight: 800,
      lineHeight: 1.3,
      display: "inline-block",
    },
    inactiveWordStyle: {
      color: "#FFFFFF",
    },
    activeWordStyle: {
      color: "#FFE500",
      transform: "scale(1.18)",
      display: "inline-block",
      textShadow: "0 0 18px rgba(255,229,0,0.55)",
    },
    fontImport: "Poppins",
  },

  {
    id: "capcut-viral",
    name: "CapCut Viral",
    description: "Bold caps — active word in red, others yellow",
    icon: "⚡",
    category: "trending",
    wordByWord: true,
    position: "center",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "12px 16px",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "6px",
      textAlign: "center",
    },
    textStyle: {
      fontFamily: "Bangers, cursive",
      fontSize: "38px",
      textTransform: "uppercase",
      lineHeight: 1.2,
      display: "inline-block",
      letterSpacing: "1px",
    },
    inactiveWordStyle: {
      color: "#FFE135",
      textShadow: "3px 3px 0 #000, -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000",
    },
    activeWordStyle: {
      color: "#FF3B30",
      textShadow: "3px 3px 0 #000, -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000",
      transform: "scale(1.22)",
      display: "inline-block",
    },
    fontImport: "Bangers",
  },

  {
    id: "reels-pop",
    name: "Reels Pop",
    description: "White words, active glows cyan",
    icon: "📱",
    category: "trending",
    wordByWord: true,
    position: "bottom",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "10px 18px",
      background: "rgba(0,0,0,0.6)",
      borderRadius: "12px",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "6px",
    },
    textStyle: {
      fontFamily: "Inter, sans-serif",
      fontSize: "26px",
      fontWeight: 900,
      lineHeight: 1.3,
      display: "inline-block",
    },
    inactiveWordStyle: {
      color: "rgba(255,255,255,0.85)",
    },
    activeWordStyle: {
      color: "#00E5FF",
      transform: "scale(1.15)",
      display: "inline-block",
      textShadow: "0 0 16px rgba(0,229,255,0.7)",
    },
    fontImport: "Poppins",
  },

  {
    id: "tiktok-dark",
    name: "TikTok Dark",
    description: "Dim words, active pops bright white",
    icon: "🖤",
    category: "trending",
    wordByWord: true,
    position: "bottom",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "12px 22px",
      background: "rgba(0,0,0,0.8)",
      borderRadius: "10px",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "8px",
    },
    textStyle: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "26px",
      fontWeight: 700,
      lineHeight: 1.3,
      display: "inline-block",
    },
    inactiveWordStyle: {
      color: "rgba(255,255,255,0.35)",
    },
    activeWordStyle: {
      color: "#FFFFFF",
      transform: "scale(1.2)",
      display: "inline-block",
      textShadow: "0 0 20px rgba(255,255,255,0.5)",
    },
    fontImport: "Poppins",
  },

  {
    id: "fire-energy",
    name: "Fire Energy",
    description: "White words, active burns orange",
    icon: "🔥",
    category: "trending",
    wordByWord: true,
    position: "bottom",
    animationClass: "caption-bounce",
    containerStyle: {
      padding: "10px 20px",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "6px",
    },
    textStyle: {
      fontFamily: "Oswald, sans-serif",
      fontSize: "32px",
      fontWeight: 700,
      textTransform: "uppercase",
      lineHeight: 1.2,
      display: "inline-block",
    },
    inactiveWordStyle: {
      color: "#FFFFFF",
      textShadow: "2px 2px 0 #000",
    },
    activeWordStyle: {
      color: "#FF6B00",
      transform: "scale(1.2)",
      display: "inline-block",
      textShadow: "0 0 16px #FF6B00, 0 0 30px #FF3D00, 2px 2px 0 #000",
    },
    fontImport: "Oswald",
  },

  {
    id: "boxed-words",
    name: "Boxed Words",
    description: "Active word gets a colored box",
    icon: "📦",
    category: "trending",
    wordByWord: true,
    position: "bottom",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "8px 12px",
      display: "flex",
      flexWrap: "wrap",
      gap: "6px",
      justifyContent: "center",
    },
    textStyle: {
      fontFamily: "Poppins, sans-serif",
      fontSize: "24px",
      fontWeight: 700,
      lineHeight: 1.3,
    },
    inactiveWordStyle: {
      color: "#FFFFFF",
      background: "rgba(255,255,255,0.1)",
      padding: "4px 10px",
      borderRadius: "6px",
      display: "inline-block",
    },
    activeWordStyle: {
      color: "#FFFFFF",
      background: "#6366F1",
      padding: "4px 10px",
      borderRadius: "6px",
      display: "inline-block",
      transform: "scale(1.12)",
      boxShadow: "0 4px 18px rgba(99,102,241,0.55)",
    },
    fontImport: "Poppins",
  },

  {
    id: "karaoke-sync",
    name: "Karaoke Sync",
    description: "Dark pill, active word gold",
    icon: "🎤",
    category: "trending",
    wordByWord: true,
    position: "bottom",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "10px 20px",
      background: "rgba(0,0,0,0.75)",
      borderRadius: "10px",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "6px",
    },
    textStyle: {
      fontFamily: "Inter, sans-serif",
      fontSize: "26px",
      fontWeight: 800,
      lineHeight: 1.3,
      display: "inline-block",
    },
    inactiveWordStyle: {
      color: "#FFFFFF",
    },
    activeWordStyle: {
      color: "#FFD700",
      transform: "scale(1.15)",
      display: "inline-block",
      textShadow: "0 0 14px rgba(255,215,0,0.7)",
    },
  },

  {
    id: "alight-neon",
    name: "Alight Neon",
    description: "White words, active purple→pink",
    icon: "⚡",
    category: "creative",
    wordByWord: true,
    position: "center",
    animationClass: "caption-pop",
    containerStyle: {
      padding: "12px 20px",
      background: "rgba(0,0,0,0.55)",
      borderRadius: "16px",
      border: "1px solid rgba(168,85,247,0.25)",
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: "6px",
    },
    textStyle: {
      fontFamily: "'Poppins', sans-serif",
      fontSize: "26px",
      fontWeight: 800,
      lineHeight: 1.3,
      display: "inline-block",
    },
    inactiveWordStyle: {
      color: "rgba(255,255,255,0.45)",
    },
    activeWordStyle: {
      background: "linear-gradient(135deg, #A855F7, #EC4899)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      display: "inline-block",
      transform: "scale(1.18)",
      filter: "drop-shadow(0 0 10px rgba(168,85,247,0.8))",
    },
    fontImport: "Poppins",
  },

  // ── Sentence templates (full line, no highlight) ─────────────────────────

  {
    id: "clean-classic",
    name: "Clean Classic",
    description: "Timeless white subtitles",
    icon: "✨",
    category: "minimal",
    wordByWord: false,
    position: "bottom",
    containerStyle: { padding: "8px 20px", textAlign: "center" },
    textStyle: {
      color: "#FFFFFF",
      fontSize: "22px",
      fontFamily: "Inter, sans-serif",
      fontWeight: 700,
      textShadow: "2px 2px 8px rgba(0,0,0,0.9)",
      lineHeight: 1.4,
    },
  },

  {
    id: "subtitles-pro",
    name: "Subtitles Pro",
    description: "Clean YouTube-style subtitles",
    icon: "📺",
    category: "minimal",
    wordByWord: false,
    position: "bottom",
    containerStyle: {
      padding: "6px 20px",
      background: "rgba(8,8,8,0.82)",
      borderRadius: "4px",
      textAlign: "center",
    },
    textStyle: {
      color: "#FFFFFF",
      fontSize: "20px",
      fontFamily: "Inter, sans-serif",
      fontWeight: 600,
      lineHeight: 1.5,
    },
  },

  {
    id: "minimal-pill",
    name: "Minimal Pill",
    description: "Subtle rounded pill bar",
    icon: "💊",
    category: "minimal",
    wordByWord: false,
    position: "bottom",
    containerStyle: {
      padding: "8px 22px",
      background: "rgba(0,0,0,0.7)",
      borderRadius: "100px",
      backdropFilter: "blur(8px)",
      textAlign: "center",
    },
    textStyle: {
      color: "#F0F0F0",
      fontSize: "18px",
      fontFamily: "Inter, sans-serif",
      fontWeight: 500,
      lineHeight: 1.5,
    },
  },

  {
    id: "mrbeast",
    name: "MrBeast",
    description: "Massive yellow bold all-caps",
    icon: "👑",
    category: "bold",
    wordByWord: false,
    position: "bottom",
    containerStyle: { padding: "10px 24px", textAlign: "center" },
    textStyle: {
      color: "#FFE500",
      fontSize: "38px",
      fontFamily: "'Bangers', cursive",
      fontWeight: 400,
      textTransform: "uppercase",
      letterSpacing: "2px",
      WebkitTextStroke: "3px #000",
      textShadow: "4px 4px 0 #000",
      lineHeight: 1.1,
    },
    fontImport: "Bangers",
  },

  {
    id: "street-impact",
    name: "Street Impact",
    description: "Heavy impact, street style",
    icon: "💥",
    category: "bold",
    wordByWord: false,
    position: "center",
    containerStyle: { padding: "8px 16px", textAlign: "center" },
    textStyle: {
      color: "#FFFFFF",
      fontSize: "34px",
      fontFamily: "Oswald, sans-serif",
      fontWeight: 900,
      textTransform: "uppercase",
      letterSpacing: "4px",
      WebkitTextStroke: "2.5px #000",
      textShadow: "4px 4px 0 #000",
      lineHeight: 1.2,
    },
    fontImport: "Oswald",
  },

  {
    id: "neon-nights",
    name: "Neon Nights",
    description: "Cyberpunk cyan glow",
    icon: "💎",
    category: "creative",
    wordByWord: false,
    position: "center",
    containerStyle: {
      padding: "14px 28px",
      background: "rgba(0,0,0,0.4)",
      borderRadius: "8px",
      border: "1px solid rgba(0,255,255,0.2)",
      textAlign: "center",
    },
    textStyle: {
      color: "#00FFFF",
      fontSize: "24px",
      fontFamily: "Orbitron, sans-serif",
      fontWeight: 700,
      letterSpacing: "3px",
      textShadow: "0 0 10px #00FFFF, 0 0 20px #00FFFF, 0 0 40px #0088FF",
      lineHeight: 1.4,
    },
    fontImport: "Orbitron",
  },

  {
    id: "gradient-wave",
    name: "Gradient Wave",
    description: "Rainbow gradient text",
    icon: "🌊",
    category: "creative",
    wordByWord: false,
    position: "center",
    containerStyle: { padding: "12px 20px", textAlign: "center" },
    textStyle: {
      fontSize: "28px",
      fontFamily: "Poppins, sans-serif",
      fontWeight: 800,
      background: "linear-gradient(90deg, #FF6B6B, #FFE66D, #4ECDC4, #45B7D1, #6366F1)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      filter: "drop-shadow(2px 3px 4px rgba(0,0,0,0.8))",
      lineHeight: 1.4,
    },
    fontImport: "Poppins",
  },
];

export function getTemplateById(id: string): CaptionTemplate {
  return CAPTION_TEMPLATES.find((t) => t.id === id) ?? CAPTION_TEMPLATES[0];
}
